### ISSUE TITLE
大佬 这个带不带php7.4的环境？我想装旧版本的typecho，因为主题不支持新版本

### ISSUE THREAD

**Issue by himonster1** [JohnsonRan/Typecho-Docker#2]
旧版本typecho只能用php7吧？

**Comment by JohnsonRan** [comment]
> 旧版本typecho只能用php7吧？

把 `app/php/Dockerfile` 里第一行from改成需要的版本重新编译即可

**Comment by himonster1** [comment]
阿里嘎多

**Comment by himonster1** [comment]
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/77065609/218296331-598c95db-94bc-4ef6-8f21-e82943191a20.png">
大佬 数据库名填啥

**Comment by JohnsonRan** [comment]
> <img width="1097" alt="image" src="https://user-images.githubusercontent.com/77065609/218296331-598c95db-94bc-4ef6-8f21-e82943191a20.png">
> 
> 大佬 数据库名填啥

看你自己

**Comment by himonster1** [comment]
随便写好像不行 这个数据库名在哪看？要先去mysql里面新建一个吗

**Comment by JohnsonRan** [comment]
> 随便写好像不行 这个数据库名在哪看？要先去mysql里面新建一个吗

试试呗
